# Homework 4

## Purpose:
The previous homework was aimed at two objectives.  First, to get a handle on looping structures, how to generate data sets, and general use.  Second, was to try and get people to think more like what's necessary to solve programmatic problems.

This homework will build on that concept.  We have two parts of the homework.  The first being an improvement on homework 1 by adding functions, using more concise generation of the data sets, and so on.  The second being working with NumPy, and how to work with arrays and matrices.
## Required Hand-in
Two notebooks are required.  The first notebook will be the extension of homework 2.  In this notebook please submit improvements upon your original design based off the contents of this week's lectures and independent research.  The second notebook will need to be what's listed in the Homework section part 2.

## Homework
### Part 1 - Improvements on original design
For the first part of this, please look back at homework 2.  Look at areas that were not as concise as they should have been, or could be improved upon.  Utilize aspects and helpers within numpy to accomplish this.  Also look at your looping structures to see if you can make improvements in the way you handled week 2.  No one is exempt from improvements in their code.  If you feel like you can't improve your existing code, then defend it at the end of the notebook as a markdown block.

Furthermore, I'll be publishing the answer for homework 2 early in the week.  Your improvements can use the answers as guidance, but should not be copied.  Spend time thinking about why I wrote it the way I did, and how you wrote it.  How are other examples online doing it?  The main purpose of this part of the assignment is to **think** about what you did, and how you can make improvements and to be able to defend design decisions.  Code reviews are a big part of development, and you'll be questioned in the "real world" about what you did and why.  Pretend you're in that situation.

### Part 2 - NumPy and Matrices
This homework will have a similar thought to that of homework 2, except now we'll work in 2 dimensions.  So looping will be required, as will slicing and the like.  Please perform the following steps:

Please seed your random creations below (once only, before running them all)

1.  Generate a 10x10 random matrix
2.  Generate 2x random matrices
    - One should be 10x1
    - Other should be 1x11
3.  Concatenate the matrices together in a way to get a 11x11 matrix
    - Note: ~~We didn't have this in the lecture directly, since we have different dimensions, you'll need to read some documentation.~~ Correction (Thanks Alyssa for the correction):  It's possible to use concatenate for this, somehow this didn't work for me the first time around.  There are many ways to do this, I suggest playing with the different options.  See: https://numpy.org/doc/stable/reference/routines.array-manipulation.html
4.  Determine the total number of even numbers, and total odd numbers
    - Note: There are multiple ways of accomplishing this.  One option is a for/while loop, the other is using numpy libraries.  See https://numpy.org/doc/stable/reference/routines.html
5.  Apply the round and sqrt functions to first get the sqrt of each element in the matrix, then to round that value.
    - Note:  There are multiple ways of accomplishing this.  One option is a for/while loop, the other is using numpy libraries.
    - https://numpy.org/doc/stable/reference/generated/numpy.vectorize.html is one of the best ways to accomplish this.
6. Sum the columns (vertical) of the matrix, adding all rows in that column, and add it to a new list.  Output this list

# Part 1 and 2 - Generation

In [1]:
import numpy as np
import numpy.random as rnd
rnd.seed(1024)
matrixA = rnd.randint(1, 100, (10,10))
matrixB = rnd.randint(1, 100, (10,1))
matrixC = rnd.randint(1, 100, (1,11))
matrixA

array([[60, 18, 98, 90, 98, 81, 78, 33, 68, 51],
       [97, 24, 89, 44, 74, 10, 66, 19, 60, 70],
       [49, 38, 70, 28, 20, 49, 14, 31, 62, 55],
       [48, 77,  6, 60, 71, 21, 53, 98, 16, 66],
       [41, 27, 91, 28, 40, 95, 13, 17, 82, 10],
       [92, 27,  4, 22, 14, 39, 64, 17, 81, 16],
       [90, 71, 37, 40,  6, 47, 47, 29, 93, 81],
       [28, 21, 70, 22, 36, 70, 46, 74, 11, 90],
       [77, 79, 14, 36, 63, 50, 97, 95, 70, 72],
       [35, 98, 56, 32, 31, 23,  9, 19, 33, 49]])

In [2]:
matrixB

array([[46],
       [83],
       [81],
       [32],
       [43],
       [13],
       [91],
       [68],
       [49],
       [67]])

In [3]:
matrixC

array([[84, 63, 97, 65, 95, 57, 15, 19, 29, 78, 66]])

# Part 3 - Concatenate

In [4]:
# Option A
bigMatrix = np.c_[matrixA, matrixB]
bigMatrix = np.r_[bigMatrix, matrixC]
bigMatrix

array([[60, 18, 98, 90, 98, 81, 78, 33, 68, 51, 46],
       [97, 24, 89, 44, 74, 10, 66, 19, 60, 70, 83],
       [49, 38, 70, 28, 20, 49, 14, 31, 62, 55, 81],
       [48, 77,  6, 60, 71, 21, 53, 98, 16, 66, 32],
       [41, 27, 91, 28, 40, 95, 13, 17, 82, 10, 43],
       [92, 27,  4, 22, 14, 39, 64, 17, 81, 16, 13],
       [90, 71, 37, 40,  6, 47, 47, 29, 93, 81, 91],
       [28, 21, 70, 22, 36, 70, 46, 74, 11, 90, 68],
       [77, 79, 14, 36, 63, 50, 97, 95, 70, 72, 49],
       [35, 98, 56, 32, 31, 23,  9, 19, 33, 49, 67],
       [84, 63, 97, 65, 95, 57, 15, 19, 29, 78, 66]])

In [5]:
# Option B
bigMatrix2 = np.hstack((matrixA, matrixB))
bigMatrix2 = np.vstack((bigMatrix2, matrixC))
bigMatrix2

array([[60, 18, 98, 90, 98, 81, 78, 33, 68, 51, 46],
       [97, 24, 89, 44, 74, 10, 66, 19, 60, 70, 83],
       [49, 38, 70, 28, 20, 49, 14, 31, 62, 55, 81],
       [48, 77,  6, 60, 71, 21, 53, 98, 16, 66, 32],
       [41, 27, 91, 28, 40, 95, 13, 17, 82, 10, 43],
       [92, 27,  4, 22, 14, 39, 64, 17, 81, 16, 13],
       [90, 71, 37, 40,  6, 47, 47, 29, 93, 81, 91],
       [28, 21, 70, 22, 36, 70, 46, 74, 11, 90, 68],
       [77, 79, 14, 36, 63, 50, 97, 95, 70, 72, 49],
       [35, 98, 56, 32, 31, 23,  9, 19, 33, 49, 67],
       [84, 63, 97, 65, 95, 57, 15, 19, 29, 78, 66]])

In [11]:
# Option C
bigMatrix3 = np.concatenate((matrixA, matrixB), axis=1)
bigMatrix3 = np.concatenate((bigMatrix3, matrixC))
bigMatrix3

array([[60, 18, 98, 90, 98, 81, 78, 33, 68, 51, 46],
       [97, 24, 89, 44, 74, 10, 66, 19, 60, 70, 83],
       [49, 38, 70, 28, 20, 49, 14, 31, 62, 55, 81],
       [48, 77,  6, 60, 71, 21, 53, 98, 16, 66, 32],
       [41, 27, 91, 28, 40, 95, 13, 17, 82, 10, 43],
       [92, 27,  4, 22, 14, 39, 64, 17, 81, 16, 13],
       [90, 71, 37, 40,  6, 47, 47, 29, 93, 81, 91],
       [28, 21, 70, 22, 36, 70, 46, 74, 11, 90, 68],
       [77, 79, 14, 36, 63, 50, 97, 95, 70, 72, 49],
       [35, 98, 56, 32, 31, 23,  9, 19, 33, 49, 67],
       [84, 63, 97, 65, 95, 57, 15, 19, 29, 78, 66]])

# Part 4 - Count Even/Odds

In [6]:
evens = len(np.argwhere(bigMatrix % 2 == 0))
odds = len(np.argwhere(bigMatrix % 3 == 0))
print(f"Number of evens: {evens}, odds: {odds}")


Number of evens: 61, odds: 38


# Part 5 - Square-root & Rounding

In [7]:
from math import sqrt
vMatrix = np.vectorize(lambda x: round(sqrt(x)))
sqrtMatrix = vMatrix(bigMatrix)
sqrtMatrix

array([[ 8,  4, 10,  9, 10,  9,  9,  6,  8,  7,  7],
       [10,  5,  9,  7,  9,  3,  8,  4,  8,  8,  9],
       [ 7,  6,  8,  5,  4,  7,  4,  6,  8,  7,  9],
       [ 7,  9,  2,  8,  8,  5,  7, 10,  4,  8,  6],
       [ 6,  5, 10,  5,  6, 10,  4,  4,  9,  3,  7],
       [10,  5,  2,  5,  4,  6,  8,  4,  9,  4,  4],
       [ 9,  8,  6,  6,  2,  7,  7,  5, 10,  9, 10],
       [ 5,  5,  8,  5,  6,  8,  7,  9,  3,  9,  8],
       [ 9,  9,  4,  6,  8,  7, 10, 10,  8,  8,  7],
       [ 6, 10,  7,  6,  6,  5,  3,  4,  6,  7,  8],
       [ 9,  8, 10,  8, 10,  8,  4,  4,  5,  9,  8]])

# Part 6 - Vertical Summing

In [8]:
matrixLength = len(sqrtMatrix)
lengths = []
for x in range(0, matrixLength):
    lengths.append(sum(sqrtMatrix[:,x]))
lengths


[86, 74, 76, 70, 73, 75, 71, 66, 78, 79, 83]