# Homework 4

## Purpose:
The previous homework assignments were designed to create a solid foundation for going further in Python.  NumPy is our first "real" 3rd party module that we'll start using.

## Required Hand-in
Only one notebook is required for this particular homework.  Like all homeworks, each step flows into the next step.  Meaning, the output of step 1/2 is used in step 3.  The matrix from step 3 is used in step 4.  Step 4 -> step 5.  And so on.  All homeworks will follow a similar format, unless otherwise stated.

## Homework

### Part 1 - NumPy and Matrices
This homework will have a similar thought to that of homework 2, except now we'll work in 2 dimensions.  So looping will be required, as will slicing and the like.  Please perform the following steps:

Please seed your random creations below (once only, before running them all)

1.  Generate a 10x10 random matrix
2.  Generate 2x random matrices
    - One should be 10x1
    - Other should be 1x11
3.  Concatenate the matrices (from step 1 and 2) together in a way to get a 11x11 matrix
    - Note: We didn't have this in the lecture directly, since we have different dimensions, you'll need to read some documentation.  See: https://numpy.org/doc/stable/reference/routines.array-manipulation.html
4.  Determine the total number of even numbers, and total odd numbers
    - Note: There are multiple ways of accomplishing this.  One option is a for/while loop, the other is using numpy libraries.  See https://numpy.org/doc/stable/reference/routines.html
5.  Apply the round and sqrt functions to first get the sqrt of each element in the matrix, then to round that value.
    - Note:  There are multiple ways of accomplishing this.  One option is a for/while loop, the other is using numpy libraries.
    - https://numpy.org/doc/stable/reference/generated/numpy.vectorize.html is one of the best ways to accomplish this.
6. Sum the columns (vertical) of the matrix, adding all rows in that column, and add it to a new list.  Output this list

# Part 1 and 2 - Generation

array([[60, 18, 98, 90, 98, 81, 78, 33, 68, 51],
       [97, 24, 89, 44, 74, 10, 66, 19, 60, 70],
       [49, 38, 70, 28, 20, 49, 14, 31, 62, 55],
       [48, 77,  6, 60, 71, 21, 53, 98, 16, 66],
       [41, 27, 91, 28, 40, 95, 13, 17, 82, 10],
       [92, 27,  4, 22, 14, 39, 64, 17, 81, 16],
       [90, 71, 37, 40,  6, 47, 47, 29, 93, 81],
       [28, 21, 70, 22, 36, 70, 46, 74, 11, 90],
       [77, 79, 14, 36, 63, 50, 97, 95, 70, 72],
       [35, 98, 56, 32, 31, 23,  9, 19, 33, 49]])

array([[46],
       [83],
       [81],
       [32],
       [43],
       [13],
       [91],
       [68],
       [49],
       [67]])

array([[84, 63, 97, 65, 95, 57, 15, 19, 29, 78, 66]])

# Part 3 - Concatenate

array([[60, 18, 98, 90, 98, 81, 78, 33, 68, 51, 46],
       [97, 24, 89, 44, 74, 10, 66, 19, 60, 70, 83],
       [49, 38, 70, 28, 20, 49, 14, 31, 62, 55, 81],
       [48, 77,  6, 60, 71, 21, 53, 98, 16, 66, 32],
       [41, 27, 91, 28, 40, 95, 13, 17, 82, 10, 43],
       [92, 27,  4, 22, 14, 39, 64, 17, 81, 16, 13],
       [90, 71, 37, 40,  6, 47, 47, 29, 93, 81, 91],
       [28, 21, 70, 22, 36, 70, 46, 74, 11, 90, 68],
       [77, 79, 14, 36, 63, 50, 97, 95, 70, 72, 49],
       [35, 98, 56, 32, 31, 23,  9, 19, 33, 49, 67],
       [84, 63, 97, 65, 95, 57, 15, 19, 29, 78, 66]])

# Part 4 - Count Even/Odds

Number of evens: 61, odds: 38


# Part 5 - Square-root & Rounding

array([[ 8,  4, 10,  9, 10,  9,  9,  6,  8,  7,  7],
       [10,  5,  9,  7,  9,  3,  8,  4,  8,  8,  9],
       [ 7,  6,  8,  5,  4,  7,  4,  6,  8,  7,  9],
       [ 7,  9,  2,  8,  8,  5,  7, 10,  4,  8,  6],
       [ 6,  5, 10,  5,  6, 10,  4,  4,  9,  3,  7],
       [10,  5,  2,  5,  4,  6,  8,  4,  9,  4,  4],
       [ 9,  8,  6,  6,  2,  7,  7,  5, 10,  9, 10],
       [ 5,  5,  8,  5,  6,  8,  7,  9,  3,  9,  8],
       [ 9,  9,  4,  6,  8,  7, 10, 10,  8,  8,  7],
       [ 6, 10,  7,  6,  6,  5,  3,  4,  6,  7,  8],
       [ 9,  8, 10,  8, 10,  8,  4,  4,  5,  9,  8]])

# Part 6 - Vertical Summing

[86, 74, 76, 70, 73, 75, 71, 66, 78, 79, 83]