In [2]:

type(f"something")

str

In [3]:
someValue = f"something something, foo"

In [4]:
someValue

'something something, foo'

In [5]:
someValue = 500
someString = f"someValue = {someValue}"

In [6]:
someString

'someValue = 500'

In [7]:
someSequence = range(0, 10)

In [8]:
type(someSequence)

range

In [11]:
someList = [f"seq {x}" for x in someSequence]

In [12]:
someList[0]


'seq 0'

In [14]:
someList = []
for x in someSequence:
    someList.append("seq " + str(x))
someList

['seq 0',
 'seq 1',
 'seq 2',
 'seq 3',
 'seq 4',
 'seq 5',
 'seq 6',
 'seq 7',
 'seq 8',
 'seq 9']

In [17]:
counter = 0
someList = []
someSequence = list(someSequence)
while counter < 10:
    someList.append("seq " + str(someSequence[counter]))
    # counter += 1
someList

KeyboardInterrupt: 

In [19]:

# [ (v1, v2), (y1, y2), ...]

v1 = range(1, 10)
v2 = range(1, 10)

In [21]:
list(zip(v1, v2))

[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)]

In [22]:
[(v1[x], v2[x]) for x in range(0, len(v1))]

[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)]

In [23]:
c = 0
tList = []
while c < len(v1):
    tList.append((v1[c], v2[c]))
    c += 1
tList

[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)]

In [25]:
evens = 0
odds = 0
for x in tList:
    element = x[0]
    if element % 2 == 0:
        evens = evens + 1
    else:
        odds = odds + 1

KeyboardInterrupt: 

In [30]:
counts = {}
count = 0
while count < len(tList):
    element = tList[count][0]
    index = element % 2
    sElement = str(index)
    if sElement in counts:
        counts[sElement] = counts[sElement] + 1
    else:
        counts[sElement] = 1
    count += 1
counts

{'1': 5, '0': 4}

# Problem 2

In [31]:
myRange = range(0, 10)
for x in myRange:
    print(f"x is {x}")

x is 0
x is 1
x is 2
x is 3
x is 4
x is 5
x is 6
x is 7
x is 8
x is 9


In [33]:
myRange = [1, 5, 9, 20, 33]
v = len(myRange)
for x in myRange:
    print(f"x is {v}")
    v = v - 1

x is 5
x is 4
x is 3
x is 2
x is 1


In [36]:
for x in myRange[::-1]:
    print(f"x is {x}")

x is 33
x is 20
x is 9
x is 5
x is 1


In [38]:
myRange.reverse()
for x in myRange:
    print(f"x is {x}")

x is 1
x is 5
x is 9
x is 20
x is 33


In [40]:
myRange = [1, 5, 9, 20, 33]
counter = 4
while counter >= 0:
    print(f"x is {myRange[counter]}")
    counter = counter - 1

x is 33
x is 20
x is 9
x is 5
x is 1


In [41]:
myRange = [1, 5, 9, 20, 33]
counter = 4
for i in range(5, 0, -1):
    print(f"x is {myRange[counter]}")
    counter = counter - 1

x is 33
x is 20
x is 9
x is 5
x is 1


In [44]:
myRange = [1, 5, 9, 20, 33]
for i in range(len(myRange)-1, -1, -1):
    print(f"x is {myRange[i]}")

x is 33
x is 20
x is 9
x is 5
x is 1


In [53]:
divisionRange = []
for i in range(len(myRange)-1, -1, -1):
    topElement = myRange[i]
    slice = myRange[0:i]
    if len(slice) == 0:
        slice = [1]
    divisionRange.append(topElement/sum(slice))

divisionRange

[0.9428571428571428, 1.3333333333333333, 1.5, 5.0, 1.0]

# Problem 3

In [54]:
import numpy as np

In [81]:
matrix = np.random.randint(1, 10, (10, 10))
matrix

array([[3, 8, 4, 9, 8, 4, 9, 7, 1, 4],
       [5, 8, 7, 1, 4, 1, 2, 6, 2, 5],
       [2, 2, 4, 3, 1, 3, 4, 7, 1, 8],
       [9, 5, 7, 6, 9, 1, 1, 9, 4, 1],
       [1, 2, 7, 4, 8, 9, 7, 6, 1, 5],
       [4, 1, 7, 1, 4, 6, 9, 3, 3, 8],
       [3, 5, 4, 1, 7, 3, 6, 9, 2, 8],
       [3, 2, 6, 5, 7, 6, 9, 2, 8, 7],
       [3, 8, 6, 2, 8, 9, 4, 6, 9, 1],
       [4, 4, 9, 7, 7, 1, 4, 6, 2, 5]])

In [57]:
matrix[0,0]

6

In [58]:
matrix[0,:]

array([6, 6, 5, 7, 1, 9, 1, 1, 8, 9])

In [59]:
matrix[:,0]

array([6, 4, 1, 3, 6, 3, 6, 8, 1, 4])

In [62]:
for x in range(0, len(matrix)):
    # matrix[:,0]
    column = matrix[:, x]
    print(f"column: {column}")

column: [6 4 1 3 6 3 6 8 1 4]
column: [6 5 7 3 8 7 8 6 4 4]
column: [5 9 9 6 1 4 2 6 2 1]
column: [7 4 9 8 6 8 6 1 8 1]
column: [1 1 6 8 9 2 3 1 5 7]
column: [9 5 3 5 1 3 5 9 4 7]
column: [1 6 5 3 9 1 1 9 1 7]
column: [1 4 7 1 7 7 2 4 7 7]
column: [8 1 3 2 7 4 1 6 3 4]
column: [9 8 2 1 6 5 9 9 7 1]


In [67]:
[f"column: {matrix[:, x]}" for x in  range(0, len(matrix))]

['column: [6 4 1 3 6 3 6 8 1 4]',
 'column: [6 5 7 3 8 7 8 6 4 4]',
 'column: [5 9 9 6 1 4 2 6 2 1]',
 'column: [7 4 9 8 6 8 6 1 8 1]',
 'column: [1 1 6 8 9 2 3 1 5 7]',
 'column: [9 5 3 5 1 3 5 9 4 7]',
 'column: [1 6 5 3 9 1 1 9 1 7]',
 'column: [1 4 7 1 7 7 2 4 7 7]',
 'column: [8 1 3 2 7 4 1 6 3 4]',
 'column: [9 8 2 1 6 5 9 9 7 1]']

In [70]:
# look at tomorrow
map(print(f"column: {matrix[:, x]}"), range(0, len(matrix)))

column: [9 8 2 1 6 5 9 9 7 1]


In [72]:
# diagonal
x = 0
while x < len(matrix):
    element = matrix[x,x]
    print(f"Diagonal: {element}")
    x += 1

Diagonal: 6
Diagonal: 5
Diagonal: 9
Diagonal: 8
Diagonal: 9
Diagonal: 3
Diagonal: 1
Diagonal: 4
Diagonal: 3
Diagonal: 1


In [75]:
matrix

array([[6, 6, 5, 7, 1, 9, 1, 1, 8, 9],
       [4, 5, 9, 4, 1, 5, 6, 4, 1, 8],
       [1, 7, 9, 9, 6, 3, 5, 7, 3, 2],
       [3, 3, 6, 8, 8, 5, 3, 1, 2, 1],
       [6, 8, 1, 6, 9, 1, 9, 7, 7, 6],
       [3, 7, 4, 8, 2, 3, 1, 7, 4, 5],
       [6, 8, 2, 6, 3, 5, 1, 2, 1, 9],
       [8, 6, 6, 1, 1, 9, 9, 4, 6, 9],
       [1, 4, 2, 8, 5, 4, 1, 7, 3, 7],
       [4, 4, 1, 1, 7, 7, 7, 7, 4, 1]])

In [98]:
# applying math to matrix
x = 0
while x < len(matrix):
    slice = matrix[:, x]
    print(f"Before: {slice}")
    slice = slice / 2
    print(f"After: {slice}")
    x = x+1

Before: [14 16 18  4  8 14 12 16 18 12]
After: [7. 8. 9. 2. 4. 7. 6. 8. 9. 6.]
Before: [10  8 12  2 18 18  8  8 18  4]
After: [5. 4. 6. 1. 9. 9. 4. 4. 9. 2.]
Before: [14  4 12 12 16 16 16 14 12 12]
After: [7. 2. 6. 6. 8. 8. 8. 7. 6. 6.]
Before: [12  2 18 18 16 14 10  8  4 18]
After: [6. 1. 9. 9. 8. 7. 5. 4. 2. 9.]
Before: [18 12 16 12 14 14  2 14  4 10]
After: [9. 6. 8. 6. 7. 7. 1. 7. 2. 5.]
Before: [ 4 12  6  6  6  8 18  6 12 10]
After: [2. 6. 3. 3. 3. 4. 9. 3. 6. 5.]
Before: [16 18 18  4 12 10 10  2 14 10]
After: [8. 9. 9. 2. 6. 5. 5. 1. 7. 5.]
Before: [18  4 16 16  8  8  6  4  4 18]
After: [9. 2. 8. 8. 4. 4. 3. 2. 2. 9.]
Before: [ 8 14 18  8 16  2  8  4 18 10]
After: [4. 7. 9. 4. 8. 1. 4. 2. 9. 5.]
Before: [18  8  6 14 12  6  4 14  4 18]
After: [9. 4. 3. 7. 6. 3. 2. 7. 2. 9.]


In [99]:
matrix = np.random.randint(1, 10, (10, 10))
matrix

array([[9, 4, 6, 2, 9, 8, 6, 9, 7, 7],
       [8, 5, 2, 2, 7, 7, 2, 6, 9, 1],
       [4, 2, 3, 7, 3, 6, 9, 8, 4, 4],
       [1, 4, 3, 8, 9, 3, 1, 2, 4, 8],
       [2, 3, 2, 1, 8, 2, 7, 3, 2, 7],
       [7, 2, 6, 5, 5, 7, 7, 1, 8, 8],
       [8, 9, 5, 1, 1, 8, 2, 2, 8, 9],
       [9, 7, 1, 8, 7, 8, 6, 4, 2, 3],
       [7, 6, 3, 4, 6, 9, 8, 4, 6, 4],
       [4, 6, 3, 5, 9, 1, 8, 3, 8, 3]])

In [100]:
matrix

array([[9, 4, 6, 2, 9, 8, 6, 9, 7, 7],
       [8, 5, 2, 2, 7, 7, 2, 6, 9, 1],
       [4, 2, 3, 7, 3, 6, 9, 8, 4, 4],
       [1, 4, 3, 8, 9, 3, 1, 2, 4, 8],
       [2, 3, 2, 1, 8, 2, 7, 3, 2, 7],
       [7, 2, 6, 5, 5, 7, 7, 1, 8, 8],
       [8, 9, 5, 1, 1, 8, 2, 2, 8, 9],
       [9, 7, 1, 8, 7, 8, 6, 4, 2, 3],
       [7, 6, 3, 4, 6, 9, 8, 4, 6, 4],
       [4, 6, 3, 5, 9, 1, 8, 3, 8, 3]])

In [101]:
x = 0
while x < len(matrix):
    # slice = matrix[:, x]
    # slice2 = slice * 2
    # matrix[:, x] = slice2
    matrix[:, x] = matrix[:, x] * 2
    x = x+1

In [102]:
matrix

array([[18,  8, 12,  4, 18, 16, 12, 18, 14, 14],
       [16, 10,  4,  4, 14, 14,  4, 12, 18,  2],
       [ 8,  4,  6, 14,  6, 12, 18, 16,  8,  8],
       [ 2,  8,  6, 16, 18,  6,  2,  4,  8, 16],
       [ 4,  6,  4,  2, 16,  4, 14,  6,  4, 14],
       [14,  4, 12, 10, 10, 14, 14,  2, 16, 16],
       [16, 18, 10,  2,  2, 16,  4,  4, 16, 18],
       [18, 14,  2, 16, 14, 16, 12,  8,  4,  6],
       [14, 12,  6,  8, 12, 18, 16,  8, 12,  8],
       [ 8, 12,  6, 10, 18,  2, 16,  6, 16,  6]])