In [2]:
import numpy as np

In [4]:
randMatrix = np.random.randint(1, 100, size=(8,8))
randMatrix

array([[30, 47, 52, 10, 17, 77, 37, 67],
       [23, 57, 63,  1, 68, 83, 92, 24],
       [95, 96, 20, 69, 12, 39, 47, 89],
       [39, 75, 29, 59, 65, 55, 68,  9],
       [34, 34, 54, 73, 56, 38, 11,  8],
       [29, 92, 35, 59,  4, 42, 59, 55],
       [12, 68, 28, 86, 61, 69, 87, 27],
       [95, 42, 84,  3, 14, 92, 98, 87]])

In [5]:
randMatrix = np.random.randint(1, 100, size=(8,8,3))
randMatrix

array([[[73,  2,  1],
        [ 9, 92,  9],
        [59, 81, 85],
        [ 9, 70, 37],
        [ 2, 60, 22],
        [47, 77, 21],
        [61, 29, 73],
        [ 1, 27, 30]],

       [[94, 54, 80],
        [13, 93, 90],
        [66,  8, 96],
        [52, 50, 82],
        [12, 66, 56],
        [63, 18, 72],
        [ 4, 69, 71],
        [ 7, 42, 64]],

       [[80, 52, 33],
        [11, 47, 14],
        [20, 64, 56],
        [ 9, 66, 88],
        [74, 19, 69],
        [64, 93, 89],
        [70, 56,  6],
        [60,  3, 91]],

       [[89, 86,  5],
        [47, 64, 16],
        [52, 31, 56],
        [92, 63,  9],
        [38, 27, 86],
        [89, 88, 97],
        [67,  2,  5],
        [32, 85, 32]],

       [[57, 93, 32],
        [ 7, 96, 52],
        [65, 58, 87],
        [14,  7, 30],
        [70, 47, 62],
        [12, 81, 88],
        [93, 83, 93],
        [76, 32, 91]],

       [[71, 18, 94],
        [75, 76, 14],
        [55,  9, 70],
        [38,  5, 89],
        [39,  3,  8],


In [7]:
randMatrix = np.random.randint(1, 100, size=(3,8,8))
randMatrix

array([[[22,  7, 81, 50, 45, 93, 26, 51],
        [49, 19, 86, 49, 36, 39, 35, 29],
        [ 9,  3, 45, 90, 28, 41,  9, 79],
        [36, 85, 79, 75,  5, 61, 60, 66],
        [52, 52, 78, 11, 23, 42, 87, 19],
        [87, 63, 12, 62,  9,  2, 68,  1],
        [96, 10, 25,  5, 39, 85, 60,  3],
        [31, 22,  8,  9, 85, 91, 95, 47]],

       [[ 8, 96, 16, 27, 80, 35, 72, 86],
        [ 9, 30,  3, 97, 21, 25, 52, 15],
        [26, 52, 53, 36, 28, 98, 62, 26],
        [29, 57, 19,  5, 47, 14, 11, 33],
        [72, 64, 43, 95,  5, 76, 42, 15],
        [91, 86, 43, 20, 76, 96, 67, 37],
        [91, 71, 28, 16, 92, 75, 22, 25],
        [78, 11, 39, 78, 10, 37, 43, 65]],

       [[ 3, 69, 74, 79,  4, 14, 14, 74],
        [36,  5, 68, 94, 91, 77,  2, 89],
        [66,  3, 58, 70,  4, 48,  1, 80],
        [28, 61, 48, 84, 48, 72, 71, 57],
        [71, 30, 98, 53, 76, 97, 11, 16],
        [ 8, 53,  6, 56, 79, 29, 91, 77],
        [21, 98, 19, 80, 67, 77, 29, 68],
        [ 4, 49, 76,  4,  9, 5

In [8]:
randMatrix[0,0,0]

22

In [9]:
randMatrix[1,0,0]  # first element = z coordinate/position

8

In [10]:
randMatrix[0,1,0]

49

In [12]:
randMatrix[0,:,0]   # I want this...

array([22, 49,  9, 36, 52, 87, 96, 31])

In [13]:
randMatrix[:,0,0]

array([22,  8,  3])

In [14]:
firstSlice = randMatrix[0,:,:]

In [15]:
firstSlice

array([[22,  7, 81, 50, 45, 93, 26, 51],
       [49, 19, 86, 49, 36, 39, 35, 29],
       [ 9,  3, 45, 90, 28, 41,  9, 79],
       [36, 85, 79, 75,  5, 61, 60, 66],
       [52, 52, 78, 11, 23, 42, 87, 19],
       [87, 63, 12, 62,  9,  2, 68,  1],
       [96, 10, 25,  5, 39, 85, 60,  3],
       [31, 22,  8,  9, 85, 91, 95, 47]])

In [19]:
firstSlice[:,0]

array([22, 49,  9, 36, 52, 87, 96, 31])

In [20]:
len(firstSlice)

8

In [22]:
for x in range(0, len(firstSlice)):
    print(f"Iteration {x}")

Iteration 0
Iteration 1
Iteration 2
Iteration 3
Iteration 4
Iteration 5
Iteration 6
Iteration 7


In [23]:
# This gives me the sum of the columns, and works for step 3 (sum of columns)
sumOfColumns = []
for x in range(0, len(firstSlice)):
    column = firstSlice[:,x]
    sumOfColumns.append(sum(column))
sumOfColumns

[382, 261, 414, 351, 270, 454, 440, 295]

In [26]:
test = [[1,2,3], [4, 5, 6], [7, 8, 9]]

In [27]:
test

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
# We'll have to have a 3x8 in the long run
# mySimpleMatrix = np.reshape(mySimpleMatrix, (3, 8))

In [30]:
def sliceColumnAddition(matrix, zindex = 0):
    firstSlice = randMatrix[zindex,:,:]
    sumOfColumns = []
    for x in range(0,len(firstSlice)):
        column = firstSlice[:,x]
        sumOfColumns.append(sum(column))
    return sumOfColumns

In [39]:
firstLayer = sliceColumnAddition(randMatrix)
secondLayer = sliceColumnAddition(randMatrix, 1)
thirdLayer = sliceColumnAddition(randMatrix, 2)

In [38]:
thirdLayer.append(secondLayer)
thirdLayer

[237,
 368,
 447,
 520,
 378,
 469,
 311,
 480,
 [404, 467, 244, 374, 359, 456, 371, 302],
 [404, 467, 244, 374, 359, 456, 371, 302]]

In [40]:
for x in range(0, len(secondLayer)):
    thirdLayer.append(secondLayer[x])

In [42]:
for x in firstLayer:
    thirdLayer.append(x)

In [44]:
len(thirdLayer)

24

In [45]:
mySimpleMatrix = np.reshape(thirdLayer, (3, 8))
mySimpleMatrix

array([[237, 368, 447, 520, 378, 469, 311, 480],
       [404, 467, 244, 374, 359, 456, 371, 302],
       [382, 261, 414, 351, 270, 454, 440, 295]])

In [48]:
# Final Version
def sumColumns(matrix):
    sumOfColumns = []
    for x in range(0, len(matrix)):
        column = matrix[:,x]
        sumOfColumns.append(sum(column))
    return sumOfColumns

In [49]:
sumColumns(mySimpleMatrix)

[1023, 1096, 1105]

In [56]:
# Don't use this
def sliceColumnAddition(matrix, zindex = 0):
    firstSlice = randMatrix[zindex,:,:]
    return sumColumns(firstSlice)

In [51]:
sliceColumnAddition(randMatrix)

[382, 261, 414, 351, 270, 454, 440, 295]

In [52]:
firstLayer

[382, 261, 414, 351, 270, 454, 440, 295]

In [76]:
def sliceMatrixAddition(matrix):
    zlength = len(matrix)
    xlength = len(matrix[0,:,:])
    
    counter = zlength - 1
    returnList = []
    while counter >= 0:
        matrixSlice = randMatrix[counter,:,:]
        columnAddition = sumColumns(matrixSlice)
        #returnList.append(columnAddition)
        for x in columnAddition:
            returnList.append(x)
        counter = counter - 1
    return np.reshape(returnList, (zlength, xlength))

In [77]:
sliceMatrixAddition(randMatrix)

array([[237, 368, 447, 520, 378, 469, 311, 480],
       [404, 467, 244, 374, 359, 456, 371, 302],
       [382, 261, 414, 351, 270, 454, 440, 295]])

In [67]:
len(randMatrix)

3

In [73]:
len(randMatrix[0,:,:])

8