# 03.03.01 - NumPy

## Description

This document goes over the very basics of NumPy, general initialization, accessing and so on

## Requirements
NumPy

In [1]:
import numpy as np

In [3]:
myList = range(1, 10)
mySimpleArray = np.array(myList)
mySimpleArray

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# Initialize with a dtype
myList = range(1, 10)
myFloatArray = np.array(myList, dtype=float)
myFloatArray

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [5]:
# Accessing elements
myFloatArray[0]

1.0

In [7]:
# Accessing a range
myFloatArray[-3:]

array([7., 8., 9.])

## Matrices
A matrix is a 2-dimensional array.

In [16]:
myList = range(1, 11)
mySimpleMatrix = np.array(myList)
mySimpleMatrix = np.reshape(mySimpleMatrix, (2, 5))
mySimpleMatrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [17]:
# Pulling elements out
mySimpleMatrix[0,1]  # Single element, remember 0 starting point

2

In [18]:
mySimpleMatrix[1,1]


7

In [19]:
# Pulling ranges out
mySimpleMatrix[1:]

array([[ 6,  7,  8,  9, 10]])

In [20]:
mySimpleMatrix[1, 3:]

array([ 9, 10])

In [21]:
# Assignment
mySimpleMatrix[1, 1] = 500
mySimpleMatrix

array([[  1,   2,   3,   4,   5],
       [  6, 500,   8,   9,  10]])