# 03.03.01 - NumPy

## Description

This document goes over the very basics of NumPy, general initialization, accessing and so on

## Requirements
NumPy

In [1]:
import numpy as np

In [3]:
myList = range(1, 10)
mySimpleArray = np.array(myList)
mySimpleArray

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# Initialize with a dtype
myList = range(1, 10)
myFloatArray = np.array(myList, dtype=float)
myFloatArray

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [5]:
# Accessing elements
myFloatArray[0]

1.0

In [7]:
# Accessing a range
myFloatArray[-3:]

array([7., 8., 9.])

## Matrices
A matrix is a 2-dimensional array.

In [16]:
myList = range(1, 11)
mySimpleMatrix = np.array(myList)
mySimpleMatrix = np.reshape(mySimpleMatrix, (2, 5))
mySimpleMatrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [17]:
# Pulling elements out
mySimpleMatrix[0,1]  # Single element, remember 0 starting point

2

In [18]:
mySimpleMatrix[1,1]


7

In [19]:
# Pulling ranges out
mySimpleMatrix[1:]

array([[ 6,  7,  8,  9, 10]])

In [20]:
mySimpleMatrix[1, 3:]

array([ 9, 10])

In [25]:
# Assignment
mySimpleMatrix[1, 1] = 500
mySimpleMatrix

# We can also transpose a matrix, too
mySimpleMatrix.transpose()

array([[  1,   6],
       [  2, 500],
       [  3,   8],
       [  4,   9],
       [  5,  10]])

## Generating data types

We can generate test data easier using numpy in a lot of ways.

In [23]:
randomInts = np.random.randint(1, 100, 10)
randomInts

array([ 5, 35, 29, 10, 30, 33,  9, 86, 62, 38])

In [24]:
randMatrix = np.random.randint(1, 100, size=(10,10))
randMatrix

array([[12, 21, 58, 48, 99, 74, 61, 87, 60, 16],
       [ 4, 92, 82, 26,  5,  9, 13, 67, 59, 45],
       [67, 16,  7, 33, 50, 95, 41, 54, 29, 62],
       [73, 40, 30, 28, 11, 89, 60, 26, 93, 31],
       [ 3,  5, 82, 72, 45, 31, 71, 18, 56, 13],
       [28, 92, 37, 12, 16, 65, 80, 82, 66, 76],
       [60, 48, 66, 10, 22, 76, 19, 81, 45, 94],
       [52, 27,  4,  7, 46, 69, 47, 31, 92, 40],
       [67, 22, 46, 88, 98, 21, 49, 21, 90, 69],
       [92,  8, 46, 60, 11, 59, 19,  3, 92, 72]])

## Adding and processing Arrays/matrices

In [27]:
randMatrixA = np.random.randint(1, 100, size=(10,10))
randMatrixB = np.random.randint(1, 100, size=(10,10))
randMatrixC = randMatrixA + randMatrixB  # Note we're adding the two elements
randMatrixC

array([[ 78,  52,  90, 101, 146, 168, 126, 160, 120,  94],
       [182, 113,  93,  64, 101,  88,  46, 103, 124, 102],
       [ 67, 128,  54, 178, 132, 119,  13,  78, 142, 155],
       [ 72, 128, 101, 181,  98, 120, 128,  48, 179,  23],
       [134, 140, 130, 178,  95, 133,  58, 133,  23, 100],
       [ 71, 175, 119, 143, 176, 117, 133,  73, 161, 121],
       [ 73,  41, 119, 127, 148, 124, 121,  21, 140, 123],
       [119,  74,  95, 113,  80,  83, 132, 188, 131, 169],
       [ 62,  70,  92,  41, 138, 174, 184, 150, 128,  88],
       [121,  60, 126, 124,  44, 111, 153,  51,  69, 114]])

In [33]:
randMatrixA

array([[30, 34, 83, 39, 52, 88, 31, 62, 35, 15],
       [96, 49, 84, 57, 65, 77, 18, 22, 40, 29],
       [26, 56, 25, 86, 73, 79, 11, 74, 81, 89],
       [49, 83, 91, 86, 14, 74, 39,  4, 96, 18],
       [49, 88, 88, 85, 85, 52, 46, 73,  8, 96],
       [17, 89, 63, 81, 93, 71, 54,  4, 96, 92],
       [63, 32, 54, 39, 93, 92, 70,  5, 82, 78],
       [83, 44, 16, 26, 52, 69, 56, 90, 37, 87],
       [ 4, 54, 88, 39, 81, 92, 85, 57, 92, 57],
       [50, 24, 86, 30,  7, 64, 76, 28, 50, 56]])

In [34]:
randMatrixB

array([[48, 18,  7, 62, 94, 80, 95, 98, 85, 79],
       [86, 64,  9,  7, 36, 11, 28, 81, 84, 73],
       [41, 72, 29, 92, 59, 40,  2,  4, 61, 66],
       [23, 45, 10, 95, 84, 46, 89, 44, 83,  5],
       [85, 52, 42, 93, 10, 81, 12, 60, 15,  4],
       [54, 86, 56, 62, 83, 46, 79, 69, 65, 29],
       [10,  9, 65, 88, 55, 32, 51, 16, 58, 45],
       [36, 30, 79, 87, 28, 14, 76, 98, 94, 82],
       [58, 16,  4,  2, 57, 82, 99, 93, 36, 31],
       [71, 36, 40, 94, 37, 47, 77, 23, 19, 58]])

In [32]:
# Concatenate one block on another
np.concatenate([randMatrixA, randMatrixB], axis=0)

array([[30, 34, 83, 39, 52, 88, 31, 62, 35, 15],
       [96, 49, 84, 57, 65, 77, 18, 22, 40, 29],
       [26, 56, 25, 86, 73, 79, 11, 74, 81, 89],
       [49, 83, 91, 86, 14, 74, 39,  4, 96, 18],
       [49, 88, 88, 85, 85, 52, 46, 73,  8, 96],
       [17, 89, 63, 81, 93, 71, 54,  4, 96, 92],
       [63, 32, 54, 39, 93, 92, 70,  5, 82, 78],
       [83, 44, 16, 26, 52, 69, 56, 90, 37, 87],
       [ 4, 54, 88, 39, 81, 92, 85, 57, 92, 57],
       [50, 24, 86, 30,  7, 64, 76, 28, 50, 56],
       [48, 18,  7, 62, 94, 80, 95, 98, 85, 79],
       [86, 64,  9,  7, 36, 11, 28, 81, 84, 73],
       [41, 72, 29, 92, 59, 40,  2,  4, 61, 66],
       [23, 45, 10, 95, 84, 46, 89, 44, 83,  5],
       [85, 52, 42, 93, 10, 81, 12, 60, 15,  4],
       [54, 86, 56, 62, 83, 46, 79, 69, 65, 29],
       [10,  9, 65, 88, 55, 32, 51, 16, 58, 45],
       [36, 30, 79, 87, 28, 14, 76, 98, 94, 82],
       [58, 16,  4,  2, 57, 82, 99, 93, 36, 31],
       [71, 36, 40, 94, 37, 47, 77, 23, 19, 58]])

In [ ]:
# Concatenate
np.concatenate([randMatrixA, randMatrixB], axis=1)

In [ ]:
# Concatenate 
np.concatenate([randMatrixA, randMatrixB], axis=1)

In [31]:
# Concatenate 
np.concatenate([randMatrixA, randMatrixB], axis=1)

array([[30, 34, 83, 39, 52, 88, 31, 62, 35, 15, 48, 18,  7, 62, 94, 80,
        95, 98, 85, 79],
       [96, 49, 84, 57, 65, 77, 18, 22, 40, 29, 86, 64,  9,  7, 36, 11,
        28, 81, 84, 73],
       [26, 56, 25, 86, 73, 79, 11, 74, 81, 89, 41, 72, 29, 92, 59, 40,
         2,  4, 61, 66],
       [49, 83, 91, 86, 14, 74, 39,  4, 96, 18, 23, 45, 10, 95, 84, 46,
        89, 44, 83,  5],
       [49, 88, 88, 85, 85, 52, 46, 73,  8, 96, 85, 52, 42, 93, 10, 81,
        12, 60, 15,  4],
       [17, 89, 63, 81, 93, 71, 54,  4, 96, 92, 54, 86, 56, 62, 83, 46,
        79, 69, 65, 29],
       [63, 32, 54, 39, 93, 92, 70,  5, 82, 78, 10,  9, 65, 88, 55, 32,
        51, 16, 58, 45],
       [83, 44, 16, 26, 52, 69, 56, 90, 37, 87, 36, 30, 79, 87, 28, 14,
        76, 98, 94, 82],
       [ 4, 54, 88, 39, 81, 92, 85, 57, 92, 57, 58, 16,  4,  2, 57, 82,
        99, 93, 36, 31],
       [50, 24, 86, 30,  7, 64, 76, 28, 50, 56, 71, 36, 40, 94, 37, 47,
        77, 23, 19, 58]])